DROP PROCEDURE STD_DEV@
CREATE PROCEDURE STD_DEV
  (OUT MYSTDDEV DOUBLE)
LANGUAGE SQL

BEGIN

DECLARE SAL varchar(50);
DECLARE AVGPOW real;
DECLARE POWAVG real;
DECLARE VAL real;
DECLARE COUNT1 int;

DECLARE at_end SMALLINT DEFAULT 0;                
DECLARE not_found CONDITION FOR SQLSTATE '02000';

DECLARE c1 CURSOR FOR
    SELECT SALARY FROM DB2INST1.EMPLOYEE;

DECLARE CONTINUE HANDLER FOR not_found            
    SET at_end = 1;

SET AVGPOW = 0;
SET POWAVG = 0;
SET COUNT1 = 0;

OPEN c1;
ins_loop:
    LOOP
        FETCH c1 INTO SAL;
        IF at_end <> 0 THEN
            LEAVE ins_loop;
        END IF;
        SET VAL = CAST(SAL AS real);
        SET COUNT1 = COUNT1 + 1;
        SET AVGPOW = AVGPOW + POWER(VAL, 2);
        SET POWAVG = POWAVG + VAL;
     END LOOP ins_loop;
CLOSE c1;

if COUNT1 <> 0 THEN
    SET AVGPOW = AVGPOW / COUNT1;
    SET POWAVG = POWAVG / COUNT1;
    SET POWAVG = POWER (POWAVG, 2);
    SET MYSTDDEV = sqrt(AVGPOW - POWAVG);
END IF;

END@

CALL STD_DEV(?)@